# Generated by Django 4.1.4 on 2022-12-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="myuser", table="user",),
    ]
