# Generated by Django 4.1.4 on 2022-12-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="sid",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="room socketio id"
            ),
        ),
    ]
