# Generated by Django 4.1.4 on 2022-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0002_alter_room_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="room 인덱스"
            ),
        ),
    ]
