# Generated by Django 4.1.4 on 2022-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0003_alter_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
