# Generated by Django 4.1.4 on 2022-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0004_alter_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="owner",
            field=models.CharField(max_length=128, verbose_name="방장 닉네임"),
        ),
    ]
