# Generated by Django 4.1.4 on 2022-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0005_alter_room_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="current_num",
            field=models.IntegerField(default=0, verbose_name="현재 참가 인원 수"),
        ),
    ]
