# Generated by Django 4.1.4 on 2022-12-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sockets", "0006_alter_room_current_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="tag 이름")),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={"db_table": "tag",},
        ),
        migrations.AddField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(blank=True, to="sockets.tag"),
        ),
    ]
